# src/course_engine/pack/readme.py

"""
Governance pack README generation.

This module produces a factual, human-readable README.txt
that travels with a governance pack. It makes no evaluative
or compliance claims.
"""

from datetime import datetime, timezone
from typing import Iterable, Optional

from .profiles import PackItem


def render_pack_readme(
    *,
    engine_name: str,
    engine_version: str,
    profile: str,
    pack_items: Iterable[PackItem],
    generated_at: Optional[str] = None,
) -> str:
    """
    Render the contents of README.txt for a governance pack.

    Parameters
    ----------
    engine_name : str
        Name of the engine that generated the pack.
    engine_version : str
        Engine version string.
    profile : str
        Pack profile used (minimal, qa, audit).
    pack_items : Iterable[PackItem]
        Items considered for inclusion in this pack.
    generated_at : Optional[str]
        ISO timestamp string. If not provided, one is generated.

    Returns
    -------
    str
        README.txt contents.
    """

    timestamp = (
        generated_at
        or datetime.now(timezone.utc)
        .isoformat(timespec="seconds")
        .replace("+00:00", "Z")
    )

    lines = [
        "GOVERNANCE PACK — README",
        "",
        "This directory contains a governance pack generated by Course Engine.",
        "",
        "Purpose",
        "-------",
        "This pack records declared curriculum structure and metadata as produced",
        "by the engine at generation time. It is intended to support review,",
        "quality assurance, audit, and archival workflows.",
        "",
        "What this pack DOES",
        "--------------------",
        "- Records facts generated by the engine",
        "- Makes declared structure and metadata inspectable",
        "- Supports transparent governance conversations",
        "",
        "What this pack DOES NOT do",
        "---------------------------",
        "- Judge pedagogical quality or effectiveness",
        "- Assess learner outcomes",
        "- Imply compliance, accreditation, or approval",
        "- Enforce institutional policy or standards",
        "",
        "Generation details",
        "------------------",
        f"- Engine: {engine_name}",
        f"- Version: {engine_version}",
        f"- Profile: {profile}",
        f"- Generated at (UTC): {timestamp}",
        "",
        "Pack contents (by profile)",
        "---------------------------",
    ]

    for item in pack_items:
        requirement = "required" if item.required else "optional (included if present)"
        lines.append(f"- {item.name} — {requirement}")

    lines.extend(
        [
            "",
            "Notes",
            "-----",
            "All files in this pack are generated or copied as-is by the engine.",
            "No additional interpretation or evaluation is performed at pack time.",
            "",
            "If this pack is used outside the original generation context,",
            "it should be interpreted as a snapshot of declared information",
            "at the time indicated above.",
        ]
    )

    return "\n".join(lines) + "\n"
